### ISSUE TITLE
Error! No `Localizable.strings` file found for output.

### ISSUE THREAD

**Issue by UtkuDalmaz** [Flinesoft/BartyCrouch#11]
Hello,

Why am i getting "Error! No `Localizable.strings` file found for output." ?

I use

```
if which bartycrouch > /dev/null; then
    # Incrementally update all Storyboards/XIBs strings files
    bartycrouch interfaces -p "$PROJECT_DIR"

    # Add new keys to Localizable.strings files from NSLocalizedString in code
    bartycrouch code -p "$PROJECT_DIR" -l "$PROJECT_DIR" -a
else
    echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi
```

Incrementally updated keys of file '/Users/utkudalmaz/Developer/Jemiyet/Jemiyett/tr-TR.lproj/LaunchScreen.strings'.
BartyCrouch: Successfully updated strings file(s) of Storyboard or XIB file.
Incrementally updated keys of file '/Users/utkudalmaz/Developer/Jemiyet/Jemiyett/tr-TR.lproj/Main.strings'.
BartyCrouch: Successfully updated strings file(s) of Storyboard or XIB file.
Error! No `Localizable.strings` file found for output.
Command /bin/sh failed with exit code 64

**Comment by UtkuDalmaz** [comment]
Sorry i fixed it

**Comment by dakeshi** [comment]
Did you fix it? I got the same issue in Xcode 7.3.1.

> Error! No Localizable.strings file found for output.

I install it using brew command and insert run script in my project.
Why do I still get this error?

**Comment by Dschee** [comment]
I think the problem was that he had this line in the build script:
```
bartycrouch code -p "$PROJECT_DIR" -l "$PROJECT_DIR" -a
```

This line expects to find a `Localizable.strings` file somewhere within the specified project in a localized directory (something like 'en.lproj/'). The fix is to add a `Localizable.strings` file to the project an click the localize button in Xcode.

If the error still persists, please tell us exactly where your `Localizable.strings` file is placed relativ to your projects root path.

**Comment by dakeshi** [comment]
@Dschee Thank you for your feedback.
If I'd seen comments in the run script, I'd have known what the problem is.
There is no NSLocalizedString code in my project. 
After removing that line of code you mentioned in the run script, the warnings is disappeared.

**Comment by Dschee** [comment]
I'm reopening this issue since people still seem to face it (see #27) and although it can be seen as a "user error" I still think we can do something about it. For example the easiest improvement would be to provide a better the error message which points out what to do to fix this.

@derick182: Please note that when using the `-p` command you need to provide an absolute path to the directory you want it to search within – so instead of `/` please provide something like `/Users/Derick/Projects/MyProject/Sources`.

**Comment by eirikvaa** [comment]
I realize that this issue has been closed for quite some time now. I just upgraded to the latest version of BartyCrouch, and even though I have several `Localizable.strings` files, I still get the following error message:

> Error! No input files found.
Error! No `*.strings` file found for output.
To fix this, please add a `Localizable.strings` file to your project and click the localize button for the file in Xcode. Custom names for your `*.strings` file do also work. Alternatively remove the line beginning with `bartycrouch code` in your build script to remove this feature entirely if you don't need it. See https://github.com/Flinesoft/BartyCrouch/issues/11 for further information.

For reference, this is my run script:
```
if which bartycrouch > /dev/null; then
    # Incrementally update all Storyboards/XIBs strings files
    bartycrouch interfaces -p "$PROJECT_DIR/$PROJECT_NAME"

    # Add new keys to Localizable.strings files from NSLocalizedString in code
    # -k: use un-localized value as default value for translation.
    # -s: sort by keys
    # -a: only add keys
    # -c: override comments
    bartycrouch code -p "$PROJECT_DIR/$PROJECT_NAME" -l "$PROJECT_DIR" -a -s -k -c

else
    echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi
```

**Comment by Dschee** [comment]
@eirikvaa You're right, this still is an issue. I've just tracked it down to [this](a31aef6ad183b42b7b3dfc2e5e2c07bb212594ac) commit. So, the issue was introduced by @mathebox in #67. Will revert that for now.

**Comment by Dschee** [comment]
I just reverted the commit and released version 3.10.1. This is hopefully fixed again.

**Comment by Dschee** [comment]
Please also note that there's the new option `--custom-localizable-name` documented [here](https://github.com/Flinesoft/BartyCrouch#custom-localizable-name-aka--n---custom-localizable-name-optional) if you have a Strings file with a different name than `Localizable.strings`.
